theme: jekyll-theme-minimal
title: Sample Map Website
description: Add some instructions or background here, links to ec3 etc
background: "#073642"
#logo: you can upload a jpg to the git repo and call it here i.e. image.jpg 
#You can also add a logo from an image URL, as below
#logo: https://www.lawschool.cornell.edu/_cs_apps/pt_photo_gallery/uploads/mainphotogallery/fullsizeimage/Photogallery_Ithacapage_8.png

